### ISSUE TITLE
Consider adding PDF Functionality

### ISSUE THREAD

**Issue by Mrc0113** [SolaceDev/solace-dev-codelabs#10]
Consider adding PDF functionality. 
Essentially save the codelab as a pdf and providing a link in the overview of each codelab to the PDF in case that format is preferred. 

Thread discussing technical steps for how to do this (still a WIP) 
https://groups.google.com/forum/#!topic/codelab-authors/pnnY50o82Qw

**Comment by TamimiGitHub** [comment]
https://github.com/SolaceDev/solace-dev-codelabs-site/issues/41
