### ISSUE TITLE
Remove all references to our GA property ID

### ISSUE THREAD

**Issue by blainehussey** [SolaceDev/solace-dev-codelabs#115]
Hi Team,
As discussed, we have our Google Analytics (GA) Property ID being loaded twice;

1. We have it being loaded within our Google Tag Manager (GTM) container, which is served via Netlify's Snippet Injection.
2. We also have it being loaded separately via Codelabs themselves.

Due to (2.) we're noticing the following, which is causing our analytics to be polluted;
- anyone who clones/forks the Codelabs repo then has our GA ID within their copy.
- anyone working locally, is also being tracked in GA, as we're seeing `localhost` in our analytics.
- there's also references to `netlify` which I'm assuming is from previews being viewed.

For the reasons above we need to remove any and all references to GA **UA-3921398-10** from Codelabs as soon as we can, in order to ensure we're getting the most accurate analytics.

<img width="1236" alt="Screen Shot 2021-03-18 at 1 47 33 PM" src="https://user-images.githubusercontent.com/6960616/111687816-1b578f00-8801-11eb-9997-e9718413b638.png">

Thanks again.

**Comment by TamimiGitHub** [comment]
PR #116 will resolve this
