### ISSUE TITLE
Update the Boomi getting started codelab

### ISSUE THREAD

**Issue by TamimiGitHub** [SolaceDev/solace-dev-codelabs#146]
The boomi getting started codelab does not have secure connection steps. This issue is to modify the codelab and follow the same steps here 
https://dev.to/swenhelge/securely-connecting-to-solace-cloud-from-boomi-4506

**Comment by dev-mansonthomas** [comment]
MacBook installation update

The new installer as of 28th of June 2021, uses install4J.
It search for a suitable JVM and openjdk/jre 16 doesn't work for it.

Here is how I managed to have it worked : 

Prerequisite : 
* token
* username/password
* create an environment from "Manage=> Atom=> New => envirnoment"

![image](https://user-images.githubusercontent.com/5695269/123674944-7c502380-d842-11eb-943e-a56f3c795894.png)


1. Download latest JRE 1.8 from : https://www.oracle.com/java/technologies/javase-jre8-downloads.html
Take the .tgz format 

![image](https://user-images.githubusercontent.com/5695269/123673696-11521d00-d841-11eb-859a-eb56e37aac11.png)

2. Unpack the file and copy it to  "/Library/Java/JavaVirtualMachines/"

sudo cp jre1.8.0_291.jre /Library/Java/JavaVirtualMachines/

3. Get the token from Boomi's interface as described in the current codelabs
4. run the installer : 

./atom_install64.sh -n ThomasManson -k atom-my-boomi-s-token-XYZ

5. A window application will be launched. It will be slow and unresponsive, click slowly ;)

![image](https://user-images.githubusercontent.com/5695269/123674176-99382700-d841-11eb-907e-a8c863b9638e.png)

Click Next

6. before typing on the next screen, copy your boomi's password.
Click the first field, and wait to have the focus. (you may have the multicolor mac wheel when the app is unresponsive)
Once you have it, type the email address you used for boomi's registration, use "tab" to change field, and paste your password.

![image](https://user-images.githubusercontent.com/5695269/123674433-e4ead080-d841-11eb-9481-e26854763168.png)

(The token way may work as well, but the app was so slow and unresponsive I couldn't try)

7. choose your environment

![image](https://user-images.githubusercontent.com/5695269/123674664-24b1b800-d842-11eb-8c4e-6f604f926431.png)

If you forgot to create the env, go create it, and click "back", it will refresh the env list.

8. Destination Directory 

![image](https://user-images.githubusercontent.com/5695269/123675054-97bb2e80-d842-11eb-99ce-0f3c7f5b5441.png)

Click Next

9. Alias creation 

![image](https://user-images.githubusercontent.com/5695269/123675096-a1dd2d00-d842-11eb-8945-c52e52f740d4.png)


Click Next

10. Summary

![image](https://user-images.githubusercontent.com/5695269/123675210-c1745580-d842-11eb-8e88-e7e690f25a32.png)

11. Installation completion 

![image](https://user-images.githubusercontent.com/5695269/123675263-cdf8ae00-d842-11eb-8a8d-089af0850949.png)

Click Finish

12. Check it's running

In the upper bar, you should see a new icon, and when clicking it, you should be able to click "about"

![image](https://user-images.githubusercontent.com/5695269/123675395-f385b780-d842-11eb-9914-4ef98a9ef48b.png)
![image](https://user-images.githubusercontent.com/5695269/123675460-0a2c0e80-d843-11eb-97c4-32b369ac4ed4.png)

It won't appear in the docker image list for some reasons : 

![image](https://user-images.githubusercontent.com/5695269/123675511-19ab5780-d843-11eb-9110-fd952109d568.png)

In Boomi's web interface it should appear like this : 
![image](https://user-images.githubusercontent.com/5695269/123675594-321b7200-d843-11eb-847b-75cddbb635fa.png)
(so no mention of Offline)

Following the codelabs, you should be able to test the connection, select the newly created atom, and have a successfull test.

![image](https://user-images.githubusercontent.com/5695269/123675813-7149c300-d843-11eb-8932-b6a0c794aaa6.png)

**Comment by dev-mansonthomas** [comment]
There's no longer a "notify shape"

![image](https://user-images.githubusercontent.com/5695269/123678488-a3a8ef80-d846-11eb-987d-e2d5089a524d.png)

**Comment by dev-mansonthomas** [comment]
The topic space changed for the AcmeRideShare to this : 

acme/rideshare/ride/requested/2.0.1/{start_longitude}/{start_longitude}/json/{customer_id}/{request_id}

So the publish test should be something like : 

acme/rideshare/ride/requested/2.0.1/48.858788/2.294472/json/1234/4567

**Comment by Mrc0113** [comment]
@dev-mansonthomas you're a hero 🎉

**Comment by dev-mansonthomas** [comment]
About the process of installation I've described, it doesn't seem to install an Atom through docker but more likely a standalone java application.

Maybe it's more straightforward this way : 
https://hub.docker.com/r/boomi/atom/

I've a demo about Boomi to do soon, so I won't modify my installation now, but i'll try once it's done.
