### ISSUE TITLE
Install Claat does not work

### ISSUE THREAD

**Issue by ktenzweiler** [SolaceDev/solace-dev-codelabs#167]
I tried with the go get command, I tried with go install command, I tried downloading the binary, nothing works. Can you update the codelab with working steps to show how to install claat?

**Comment by TamimiGitHub** [comment]
Hey @ktenzweiler - it looks like starting with Go v1.17 the `go get` command for installing executables is deprecated https://go.dev/doc/go-get-install-deprecation

An alternative for this, assuming you already have go installed on your machine, you can do the following 
1. Clone the google tools project repo into a google-tools directory `git clone git@github.com:googlecodelabs/tools.git google-tools`
2. Navigate to the claat command directory `cd google-tools/claat`
3. Build the claat command `go build .`. This will create a `claat` command executable that you can use.
4. Now you can update your PATH env variable (this is either done in your .bashrc, .profile, or .zshrc depending on what your shell is) `export PATH=$PATH:$HOME/google-tools/claat`. Note: this assumes you clones the google-tools repo in your $HOME directory. If cloned elsewhere, make sure you use the right path in your path export
5. After you do this, you can open up a new terminal window and executing `claat` from the command line should work

**Comment by Mrc0113** [comment]
Thanks @TamimiGitHub. Let's capture an issue to update the codelab with this info as well ;)

**Comment by Mrc0113** [comment]
Thanks @TamimiGitHub. Let's go ahead and leave this open until we update the codelab to reflect your steps above. 

@ktenzweiler please let us know if that solves your problem. Also if it doesn't can you let us know if you're using Windows, Mac or Linux?
