### ISSUE TITLE
Cannot export AsyncAPI Definition

### ISSUE THREAD

**Issue by soutchilin** [SolaceDev/solace-dev-codelabs#168]
Hi,

In the step 10, https://codelabs.solace.dev/codelabs/design-document-discover-develop-event-driven-apis/index.html?index=..%2F..index#10 attempting to download AsyncAPI definition and get:

**An error occurred
The event PaymentCharged has a topic that will not work with AsyncAPI. Topic addresses must only contain letters, numbers and one or more of the following special characters: !#$&()*+,-./:;=[]_~.**

Could it be a problem with Async API 2.0.0., because in the tutorial the generator should be installed in the version 0.53.1 that doesn't work properly either.

**Comment by TamimiGitHub** [comment]
Hey @soutchilin, thanks for reporting this and pointing it out. There is a known issue with the AsyncAPI generator and special characters ($) https://github.com/asyncapi/java-spring-cloud-stream-template/issues/208

We will be updating the instructions of this codelabs to include the new Event Portal Design import that has the dollar signs removed in the topic hierarchy and update the asyncapi generator supported version to be downloaded

**Comment by soutchilin** [comment]
Hi @TamimiGitHub , cool. Please if possible add then the info in the lab's text, if the levels should be of type literal or variable.

**Comment by CameronRushton** [comment]
[java spring cloud stream template Issue 208](https://github.com/asyncapi/java-spring-cloud-stream-template/issues/208) will not fix this problem. The java spring cloud stream repo doesn't currently have an issue tracking support for non-uri-template characters generated from topic addresses. For now, all topic addresses, including ones in our samples, should conform to the uri-template format or be alpha numeric to be safely used with asyncAPI.

**Comment by Mrc0113** [comment]
Closed by #188
