### ISSUE TITLE
broken link in boomi-v2-getting-started.md

### ISSUE THREAD

**Issue by bjb-solace** [SolaceDev/solace-dev-codelabs#193]
In "Steps to get started with Boomi", in "Setup Boomi environment", the link to Environment Management Boomi User Guide.
Visiting that link gives a page that says "The topic you are attempting to view does not exist."
This might be the new link:  https://help.boomi.com/bundle/integration/page/c-atm-Environment_management.html
Hmm, it is the same except for the random char blob at the end.

**Comment by Mrc0113** [comment]
@TamimiGitHub do you know if the link suggested above is the correct one?

**Comment by TamimiGitHub** [comment]
The link in the codelab (https://help.boomi.com/bundle/integration/page/c-atm-Environment_management_1ec94aeb-ffaf-4cec-a3b0-483c2af3967c.html) does not 404 from Boomi's help site, hence it's not caught by broken link checker. I checked the new link that @bjb-solace posted in the comment and it is the correct one. I will update the codelab and close the this issue 👍
