### ISSUE TITLE
SDKPerf download link in trace ea codelabs does not work

### ISSUE THREAD

**Issue by gregmeldrum** [SolaceDev/solace-dev-codelabs#208]
Clicking the link to download [sdkperf-jcsmp-8.4.7.13.tar.gz](https://filedrop.solace.com/support/bucket/Distributed_Tracing_EA/sdkperf-jcsmp-8.4.7.13.tar.gz) on the Distributed Tracing EA codelab page 5 (https://codelabs.solace.dev/codelabs/tracing-ea/#4) gives the following error:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>trialdownload/Distributed_Tracing_EA/sdkperf-jcsmp-8.4.7.13.tar.gz</Key>
<RequestId>DDXPZV4XMSXAM5GH</RequestId>
<HostId>hbXMPOAiYyencVmYclzD2z+vmWqUup9YHb3NnImlIzVNpDOG/Jsg3qyuSeST5zsV8sgcz6srWdo=</HostId>
</Error>
```

**Comment by Mrc0113** [comment]
Product is working to fix the link. Thanks for raising @gregmeldrum. will keep open for now.

**Comment by Mrc0113** [comment]
@gregmeldrum it should be working now. Can you double check for me?
