### ISSUE TITLE
Modifications to How to Event-Enable your REST Architecture codelab

### ISSUE THREAD

**Issue by TamimiGitHub** [SolaceDev/solace-dev-codelabs#87]
- Add docs sections https://docs.solace.com/Overviews/Microgateway-Concepts/Microgateways-Overview.htm
- Update curl command with double quotes 
- Fix turoial typo

**Comment by TamimiGitHub** [comment]
@aaron-613 I can make quick edits for those - FYI

**Comment by aaron-613** [comment]
Wow this was from a while ago. Why is no one chasing me??  :-P

**Comment by aaron-613** [comment]
Submtted PR https://github.com/SolaceDev/solace-dev-codelabs/pull/112
